### ISSUE TITLE
Discord link bottom right

### ISSUE THREAD

**Issue by elitan** [nhost/docs#3]
Just like in [AWS Amplify docs](https://docs.amplify.aws/)

Link should go to: [https://nhost.io/discord](https://nhost.io/discord)

![image](https://user-images.githubusercontent.com/331818/87405507-d4553200-c5bf-11ea-8f8d-ae49b7b7aac8.png)

**Comment by Serhazor** [comment]
Hiya, trying to run the environment but getting an error, any ideas on how to fix it? (thanks )
![image](https://user-images.githubusercontent.com/44921903/87423304-fe175480-c5d1-11ea-8c81-76c681f1de5e.png)

**Comment by elitan** [comment]
Try run `npm install` to install all npm packages.

Then run `npm run dev` again and it should work.

I have updated the README.md.

**Comment by Serhazor** [comment]
Thanks. I've managed to run the environment now and can see the page.  Do you have a button image or would one need to create it in Photoshop?

**Comment by elitan** [comment]
I uploaded a discord icon in `src/public/images/icon-discord.png` that you can use.
